version: '3.8'
services:
  db:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    container_name: 'mysql'
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  mysql-data:
