version: '3.8'
services:
  db:
    image: mariadb:10.9.2
    restart: always
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
