version: '3.8'
services:
  db:
    image: quay.io/keycloak/keycloak:22.0.1
    restart: always
    container_name: local-keycloak
    ports:
      - 9080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: password
